### ISSUE TITLE
Checking PyPI name availability

### ISSUE THREAD

**Issue by patel-zeel** [dhilipsiva/garuda#12]
Hi,

Is this library active? I am developing another library with the same name but couldn't upload it to PyPI since this library is already on PyPI. I'd be very grateful if this library is taken down from PyPI if you no longer have a use for it.

Thank you.

**Comment by dhilipsiva** [comment]
@patel-zeel sure, I can. Can you please email to dhilipsiva[at]pm[dot]me? I will transfer the ownership to you.

**Comment by patel-zeel** [comment]
Thank you @dhilipsiva! I have sent an email to you.

**Comment by dhilipsiva** [comment]
Hi, I just added you as owner to the project on PyPI. Please feel free to remove me from collaborators once you have accepted the invite. Apologies it took so long - was stuck with work. Closing this issue now.

**Comment by patel-zeel** [comment]
Thanks a lot, @dhilipsiva! No problem at all; it was timely :)
